// <auto-generated />
using System;
using CitiesManager.web.DBcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.web.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260420191447_CityNameRequired")]
    partial class CityNameRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.web.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("4eb4c0ff-b77e-449f-908b-36a719d0ba46"),
                            CityName = "New York"
                        },
                        new
                        {
                            CityId = new Guid("a269449f-b88f-47b8-9c0e-75c40bdaf66e"),
                            CityName = "Los Angeles"
                        },
                        new
                        {
                            CityId = new Guid("f5c3f77a-9af8-4c8c-a16c-4eda01bcae03"),
                            CityName = "Chicago"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
