// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDBContext))]
    [Migration("20260314070510_CleanSchema3")]
    partial class CleanSchema3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Gender", b =>
                {
                    b.Property<int>("GenderKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderKey"));

                    b.Property<bool?>("Benefits")
                        .HasColumnType("bit");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderKey");

                    b.ToTable("Genders", (string)null);

                    b.HasData(
                        new
                        {
                            GenderKey = 11,
                            Benefits = false,
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderKey = 21,
                            Benefits = true,
                            GenderName = "Female"
                        },
                        new
                        {
                            GenderKey = 31,
                            Benefits = false,
                            GenderName = "Other"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CountryID")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("GenderKey")
                        .HasColumnType("int");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("Pin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(111111)
                        .HasColumnName("PinCode");

                    b.HasKey("PersonID");

                    b.HasIndex("GenderKey");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000001"),
                            Address = "123 Maple Street, New York",
                            CountryID = "US",
                            DateOfBirth = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.johnson@example.com",
                            Gender = "Female",
                            GenderKey = 0,
                            PersonName = "Alice Johnson"
                        },
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000002"),
                            Address = "456 Oak Avenue, Chicago",
                            CountryID = "US",
                            DateOfBirth = new DateTime(1985, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.smith@example.com",
                            Gender = "Male",
                            GenderKey = 0,
                            PersonName = "Bob Smith"
                        },
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000003"),
                            Address = "789 Pine Road, San Francisco",
                            CountryID = "US",
                            DateOfBirth = new DateTime(1992, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "catherine.lee@example.com",
                            Gender = "Female",
                            GenderKey = 0,
                            PersonName = "Catherine Lee"
                        },
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000004"),
                            Address = "12 MG Road, Bengaluru",
                            CountryID = "IN",
                            DateOfBirth = new DateTime(1988, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.kumar@example.com",
                            Gender = "Male",
                            GenderKey = 0,
                            PersonName = "David Kumar"
                        },
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000005"),
                            Address = "34 Queen Street, London",
                            CountryID = "UK",
                            DateOfBirth = new DateTime(1995, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.brown@example.com",
                            Gender = "Female",
                            GenderKey = 0,
                            PersonName = "Emma Brown"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.HasOne("Entities.Gender", "Gndr")
                        .WithMany("Persons")
                        .HasForeignKey("GenderKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gndr");
                });

            modelBuilder.Entity("Entities.Gender", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
