// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDBContext))]
    [Migration("20260312153519_FilteredPersons_StoredProcedure")]
    partial class FilteredPersons_StoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CountryID")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PersonID");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000001"),
                            Address = "123 Maple Street, New York",
                            CountryID = "US",
                            DateOfBirth = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.johnson@example.com",
                            Gender = "Female",
                            PersonName = "Alice Johnson"
                        },
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000002"),
                            Address = "456 Oak Avenue, Chicago",
                            CountryID = "US",
                            DateOfBirth = new DateTime(1985, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.smith@example.com",
                            Gender = "Male",
                            PersonName = "Bob Smith"
                        },
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000003"),
                            Address = "789 Pine Road, San Francisco",
                            CountryID = "US",
                            DateOfBirth = new DateTime(1992, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "catherine.lee@example.com",
                            Gender = "Female",
                            PersonName = "Catherine Lee"
                        },
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000004"),
                            Address = "12 MG Road, Bengaluru",
                            CountryID = "IN",
                            DateOfBirth = new DateTime(1988, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.kumar@example.com",
                            Gender = "Male",
                            PersonName = "David Kumar"
                        },
                        new
                        {
                            PersonID = new Guid("00000000-0000-0000-0000-000000000005"),
                            Address = "34 Queen Street, London",
                            CountryID = "UK",
                            DateOfBirth = new DateTime(1995, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.brown@example.com",
                            Gender = "Female",
                            PersonName = "Emma Brown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
